### ISSUE TITLE
AttributeError: 'module' object has no attribute 'n_entities'

### ISSUE THREAD

**Issue by SeekPoint** [thomasmesnard/DeepMind-Teaching-Machines-to-Read-and-Comprehend#11]
rzai@rzai00:~/prj/DeepMind-Teaching-Machines-to-Read-and-Comprehend$ export DATAPATH=~/prj/DeepMind-Teaching-Machines-to-Read-and-Comprehend/

rzai@rzai00:~/prj/DeepMind-Teaching-Machines-to-Read-and-Comprehend$ python train.py deepmind_deep_lstm
Using gpu device 0: GeForce GTX 1080 (CNMeM is disabled, cuDNN 5005)
No plotting extension available.
Traceback (most recent call last):
  File "train.py", line 46, in <module>
    ds, train_stream = data.setup_datastream(path, vocab_path, config)
  File "/home/rzai/prj/DeepMind-Teaching-Machines-to-Read-and-Comprehend/data.py", line 137, in setup_datastream
    ds = QADataset(path, vocab_file, config.n_entities, need_sep_token=config.concat_ctx_and_question)
AttributeError: 'module' object has no attribute 'n_entities'
rzai@rzai00:~/prj/DeepMind-Teaching-Machines-to-Read-and-Comprehend$

**Comment by SeekPoint** [comment]
this can be fix by

rzai@rzai00:~/prj/DeepMind-Teaching-Machines-to-Read-and-Comprehend$ git diff
diff --git a/config/deepmind_deep_lstm.py b/config/deepmind_deep_lstm.py
index 10b5c9b..8fd05f3 100644
--- a/config/deepmind_deep_lstm.py
+++ b/config/deepmind_deep_lstm.py
@@ -3,7 +3,6 @@ from blocks.initialization import IsotropicGaussian, Constant

 from model.deep_lstm import Model

## 

 batch_size = 32
 sort_batch_count = 20

@@ -12,6 +11,7 @@ shuffle_questions = True
 concat_ctx_and_question = True
 concat_question_before = True

+n_entities = 550
 embed_size = 200

 lstm_size = [256, 256]
